version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'  # Changed from 6380:6379 to 6379:6379
    networks:
      - mynetwork

  celery:
    build: .
    command: celery -A schoolWebsite worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - mynetwork
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - celery
    networks:
      - mynetwork
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  flower:
    build: .
    command: celery -A schoolWebsite flower --port=5555
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - celery
    networks:
      - mynetwork
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # Added subnet configuration